version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: react-app-nginx
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
